### ISSUE TITLE
Updated cpe stuff breaks usernames and passwords specified in the test files

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/geppetto#27]
Previously, you could specify a separate username and password in the test file so that you could target another account on a given machine.  That functionality is silently broken, now.  To test on another account, you have to change the creds file.

The contents of the test file should be the last word for information.  If that information is not in the test file, then data should get pulled from the creds file.  I think the proper order of precedence should be:

1) Content specified in the target section inside the test file
2) Target Global Data from the test file
3) Creds file

If we'd like to only follow that when cpes are not specified, that's fine.

**Comment by jmartin-r7** [comment]
Closing this as addressed in #38.
